version: '3.7'

networks:
  frontend:
  backend:

services:

# -----------------------------------------------------------------
# Reverse Proxy

  traefik:
    image: traefik:v2.6
    container_name: "traefik"
    restart: unless-stopped

    networks:
      - frontend
      - backend

    ports:
      - 80:80
      - 443:443
      
    volumes:
      # Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Define Time
      - /etc/localtime:/etc/localtime:ro

       # Configuration      
      - ./devops/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./devops/traefik/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml:ro

      # Data Storage 
      - ./data/traefik/acme.json:/acme.json


# -----------------------------------------------------------------
# api.espertamente.com.br

  nodered:
    image: nodered/node-red:latest
    restart: unless-stopped
    container_name: nodered

    networks:
      - frontend
      - backend

    user: root:root
    
    environment:
      - TZ=America/Sao_Paulo
      # - NODE_RED_ENABLE_PROJECTS=true
      # - NODE_RED_CREDENTIAL_SECRET=$apr1$GCd5TkKn$PZvSTWH7UkvkszmYSaNUI/
    
    volumes:
      # Define Time
      - /etc/localtime:/etc/localtime:ro

      # Configuration
      - ./devops/nodered/settings.js:/data/settings.js
      - ./devops/nodered/public_html:/data/public_html

      # data Storage
      - ./data/nodered:/data

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nodered.rule=Host(`nodered.bee.espertamente.com.br`)"
      - "traefik.http.routers.nodered.entrypoints=websecure"

      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      
      - "traefik.http.routers.nodered.service=nodered"
      - "traefik.http.routers.nodered.tls.certresolver=letsencrypt"


# -----------------------------------------------------------------
# Grafana
# grafana.bee.espertamente.com.br

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana

    networks:
      - frontend
      - backend

    volumes:
      # Define Time
      - /etc/localtime:/etc/localtime:ro

      # Configuration
      - ./devops/grafana:/etc/grafana

      # Data Storage
      - ./devops/grafana:/var/lib/grafana

      # Log Storage
      # - ./logs/grafana/:/var/log/grafana
      
    environment:
      - GF_SECURITY_ADMIN_USER=alcides
      - GF_SECURITY_ADMIN_PASSWORD=MuitoObrigado!!!MuitoObrigado!!!MuitoObrigado!!!
      - GF_USERS_ALLOW_SIGN_UP=false
      # - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.grafana.rule=Host(`grafana.bee.espertamente.com.br`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"

      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"


# -----------------------------------------------------------------
# Mosquitto
# mqtt.bee.espertamente.com.br

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    container_name: "mosquitto"

    networks:
      - backend

    ports:
      - 1883:1883

    volumes:
      # Configuration
      - ./devops/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./devops/mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro

      # Data Storage
      - ./data/mosquitto/data:/mosquitto/data

      # Log Storage
      - ./data/mosquitto/log:/mosquitto/log
